# Makefile for Simple SDS
#
# Environment Variables:
#
# - COMPILER=pgi: select the Portland Group compilers
# - COMPILER=gcc: select the GNU Compiler Collection (default)
#
# - NC4=true: build with NetCDF4 instead of NetCDF3
# - H4=true: build with HDF version 4 support
# - H5=true: build with HDF version 5 support

ifeq ($(H5),true)
	need_h5=true
endif
ifeq ($(NC4),true)
	need_h5=true
endif

ifeq ($(COMPILER),pgi)
	PFX = pgi

	CC = pgcc
	CFLAGS = -g
	F90 = pgf90

else
	PFX = gcc

	CC = gcc
	CFLAGS = -g -Wall -std=c99 -pedantic
	F90 = gfortran
endif

ifeq ($(NC4),true)
	NC_ROOT = /usr/local/netcdf4-$(PFX)
else
	NC_ROOT = /usr/local/netcdf3-$(PFX)
endif
CFLAGS  += -I$(NC_ROOT)/include -Isrc/
LDFLAGS += -L$(NC_ROOT)/lib

H4_ROOT = /usr/local/hdf4-$(PFX)

ifeq ($(H4),true)
	CFLAGS += -I$(H4_ROOT)/include -DHAVE_HDF4
	LDFLAGS += -L$(H4_ROOT)/lib -lmfhdf -ldf -ljpeg -lz
endif

ifeq ($(NC4),true)
	CFLAGS += -DHAVE_NETCDF4
	LDFLAGS += -lnetcdff -lnetcdf
else
	LDFLAGS += -lnetcdf
endif

H5_ROOT = /usr/local/hdf5-$(PFX)
ifeq ($(need_h5),true)
	CFLAGS += -I$(H5_ROOT)/include -DHAVE_HDF5
	LDFLAGS += -L$(H5_ROOT)/lib -lhdf5_hl -lhdf5 -lz
endif

LDFLAGS += -Lsrc -lm

# ---

LIB_OBJS = \
	src/sds.o \
	src/sds_sort.o \
	src/sds-util.o \
	src/sds.o \
	src/sds_nc.o

ifeq ($(H4),true)
	LIB_OBJS += src/sds_hdf4.o
endif

NC2CODE_OBJS = \
	nc2code/nc2code.o \
	nc2code/f90.o \
	nc2code/generate_f90.o \
	nc2code/generate_simple_f90.o 

.SUFFIXES:
.SUFFIXES: .c .o

.PHONY: all test

.c.o:
	$(CC) $(CFLAGS) -c $*.c -o $*.o

all: lib sds-dump nc2code/nc2code

lib: src/libsimplesds.a

src/libsimplesds.a: $(LIB_OBJS)
	ar -ru $@ $^

sds-dump: src/libsimplesds.a sds-dump.o
	$(CC) -o $@ sds-dump.o -lsimplesds $(LDFLAGS)

nc2code/nc2code: $(LIB_OBJS) $(NC2CODE_OBJS)
	$(CC) -o $@ $^ $(LDFLAGS)

clean:
	rm -f *~ *.o
	rm -f src/*.o src/lib*.a
	rm -f nc2code/*.o nc2code/*~


# deps
src/sds.c: src/sds.h
src/sds_hdf.c: src/sds.h
src/sds_nc.c: src/sds.h
src/sds_sort.c: src/sds.h
src/sds-util.c: src/sds.h
